In [1]:
import psycopg2
import sys
import pandas as pd
import sqlalchemy
from sqlalchemy import create_engine

print(pd.__version__)
print(sqlalchemy.__version__)
print(sys.version)

2.2.2
2.0.49
3.9.25 (main, Nov  3 2025, 22:44:01) [MSC v.1929 64 bit (AMD64)]

In [7]:
db_user = "airflow"
db_password = "airflow" 
db_host = "localhost"  
db_port = "5434"  

connection = psycopg2.connect(
    user=db_user,
    password=db_password,
    host=db_host,
    port=db_port,
    database = "airflow"
)

print("Connected!")

cur = connection.cursor()
cur.execute("SELECT current_database(), current_user;")
print(cur.fetchone())

Connected!
('airflow', 'airflow')

In [9]:
cur = connection.cursor()

q = '''
CREATE TABLE table_m3 (
    id BIGINT,
    name TEXT,
    host_id BIGINT,
    host_name TEXT,
    neighbourhood_group TEXT,
    neighbourhood TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    room_type TEXT,
    price DOUBLE PRECISION,
    minimum_nights BIGINT,
    number_of_reviews BIGINT,
    last_review DATE,
    reviews_per_month DOUBLE PRECISION,
    calculated_host_listings_count BIGINT,
    availability_365 BIGINT,
    number_of_reviews_ltm BIGINT,
    license TEXT,
    city TEXT,
    scrape_date DATE
);
'''

cur.execute(q)
connection.commit()

print("table_m3 created")

table_m3 created

In [10]:
cur.execute("SELECT tablename FROM pg_tables WHERE tablename = 'table_m3';")
print(cur.fetchall())

[('table_m3',)]

In [ ]:
raw_file = 'Pdata_raw.csv'

postgres_url = "postgresql+psycopg2://airflow:airflow@localhost:5434/airflow"  # Host-machine PostgreSQL URL.

engine = create_engine(postgres_url)  # Buat SQL Alchemy engies biar pandas bisa write ke PostgreSQL.

df = pd.read_csv(raw_file, low_memory=False)  # Baca  raw CSV sesuai dengan yang di download, tanpa data cleaning dulu.
df.to_sql(
    "table_m3", 
    engine, 
    if_exists="append", 
    index=False)  # Function buat masukin data ke table_m3 postgre

print("Insert success!")

Insert success!

In [13]:
cur.execute("SELECT COUNT(*) FROM table_m3;")
print(cur.fetchall())

[(292802,)]

In [ ]:
df = pd.read_csv('data_raw.csv')
df.head(5)

C:\Users\mrich\AppData\Local\Temp\ipykernel_18812\2307710402.py:1: DtypeWarning: Columns (4,17) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('P2M3_michael_richard_data_raw.csv')

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license,city,scrape_date
0,13913,Holiday London DB Room Let-on going,54730,Alina,NaN,Islington,51.56861,-0.11270,Private room,70.0,1,55,2025-08-21,0.30,2,331,10,NaN,London,2026-03-29
1,15400,Bright Chelsea Apartment. Chelsea!,60302,Philippa,NaN,Kensington and Chelsea,51.48780,-0.16813,Entire home/apt,149.0,4,97,2025-04-05,0.51,1,199,1,NaN,London,2026-03-29
2,17402,Very Central Modern 3-Bed/2 Bath By Oxford St W1,67564,Liz,NaN,Westminster,51.52195,-0.14094,Entire home/apt,411.0,3,56,2024-02-19,0.32,2,80,0,NaN,London,2026-03-29
3,24328,Battersea live/work artist house,41759,Joe,NaN,Wandsworth,51.47072,-0.16266,Entire home/apt,NaN,7,95,2025-07-05,0.53,1,294,1,NaN,London,2026-03-29
4,36274,Bright 1 bedroom apt off brick lane in Shoreditch,133271,Hendryks,NaN,Tower Hamlets,51.52322,-0.06979,Entire home/apt,210.0,5,15,2025-09-06,0.09,2,323,6,NaN,London,2026-03-29

In [5]:
df.tail()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license,city,scrape_date
292797,1480042219847997681,Rustica Cove—Heritage Escape by Manly’s Shores,347608321,Calyn,NaN,Manly,-33.801750,151.288800,Entire home/apt,NaN,2,1,2025-08-24,1.00,16,309,1,PID-STRA-80839,Sydney,2026-03-29
292798,1480050997732404756,Modern Family Home In Paddington - 3 bedrooms,16026854,Tracey McArdle Exclusive Properties,NaN,Woollahra,-33.879040,151.227080,Entire home/apt,NaN,21,0,NaN,NaN,55,124,0,PID-STRA-79621,Sydney,2026-03-29
292799,1480052704340595354,Top Floor APT in heart of City,21151187,John,NaN,Sydney,-33.874723,151.223031,Entire home/apt,NaN,2,1,2025-08-26,1.00,22,0,1,PID-STRA-39071,Sydney,2026-03-29
292800,1480144278899031973,Two-bedroom standalone townhouse,711457600,Xuemei,NaN,Sydney,-33.917365,151.206906,Entire home/apt,NaN,1,10,2025-09-12,9.37,1,143,10,Exempt,Sydney,2026-03-29
292801,1480493397212908710,Central Burwood 2Beds | Walk to Westfield & Train,659806489,Leslie,NaN,Burwood,-33.878420,151.099180,Entire home/apt,NaN,1,4,2025-09-01,3.75,5,342,4,PID-STRA-81769,Sydney,2026-03-29

In [6]:
df.shape

(292802, 20)

In [7]:
df.isnull().sum()

id                                     0
name                                   0
host_id                                0
host_name                             90
neighbourhood_group               273392
neighbourhood                          0
latitude                               0
longitude                              0
room_type                              0
price                             152852
minimum_nights                         0
number_of_reviews                      0
last_review                        66365
reviews_per_month                  66365
calculated_host_listings_count         0
availability_365                       0
number_of_reviews_ltm                  0
license                           152949
city                                   0
scrape_date                            0
dtype: int64

In [9]:
df.duplicated().sum()

0

In [11]:
df.columns.to_list()

['id',
 'name',
 'host_id',
 'host_name',
 'neighbourhood_group',
 'neighbourhood',
 'latitude',
 'longitude',
 'room_type',
 'price',
 'minimum_nights',
 'number_of_reviews',
 'last_review',
 'reviews_per_month',
 'calculated_host_listings_count',
 'availability_365',
 'number_of_reviews_ltm',
 'license',
 'city',
 'scrape_date']

In [13]:
df.nunique()

id                                292802
name                              278076
host_id                           169174
host_name                          38242
neighbourhood_group                   10
neighbourhood                        248
latitude                          169595
longitude                         189973
room_type                              4
price                               4852
minimum_nights                       194
number_of_reviews                    891
last_review                         3976
reviews_per_month                   1218
calculated_host_listings_count       150
availability_365                     366
number_of_reviews_ltm                255
license                           107008
city                                   7
scrape_date                            1
dtype: int64